###
POST https://safety2025.duckdns.org/users/register
Content-Type: application/json

{
  "username": "name2",
  "name" : "name2",
  "password" : "pwd",
  "email" : "abc@email.com",
  "phone_number" : "01012345678",
  "member_type" : "NORMAL"
}



###
POST https://safety2025.duckdns.org/user/car/register
Content-Type: application/json

{
    "carId" : "new",
    "username" : "name1"
}


###
GET https://safety2025.duckdns.org/user/car/name1
Content-Type: application/json



###
GET https://safety2025.duckdns.org/qr/generate/name1