###
POST https://safety2025.duckdns.org/users/register
Content-Type: application/json

{
  "username": "name3",
  "name" : "name3",
  "password" : "pwd",
  "email" : "abc@email.com",
  "phone_number" : "01012345678",
  "member_type" : "NORMAL"
}



###
POST https://safety2025.duckdns.org/user/car/register
Content-Type: application/json

{
    "carId" : "jongganacar1",
    "username" : "jonggang"
}


###
GET https://safety2025.duckdns.org/user/car/name1
Content-Type: application/json



###
GET https://safety2025.duckdns.org/qr/generate/name1

###
GET http://localhost:8080/api/dev/issue-token?username=test

### username=test가
POST http://localhost:8080/api/qr/scan
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ0ZXN0IiwidXNlcklkIjozLCJ1c2VybmFtZSI6InRlc3QiLCJhdXRoIjoiTk9STUFMIiwiZXhwIjoxNzQ3ODM5MDY3fQ.JqrERa6RTK9nMoY8VYGVhnwXERvEsGSuNt-roH7dR0E-MbNdnlUFThdgUY_WOBZY
Content-Type: application/json

{
  "scannedUsername": "jonggang"
}
###
GET http://localhost:8080/companions/recent
access: eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ0ZXN0MDAwMSIsInVzZXJJZCI6NCwidXNlcm5hbWUiOiJ0ZXN0MDAwMSIsImF1dGgiOiJOT1JNQUwiLCJleHAiOjE3NDg1Mjg5MzV9.NuEpXE76466EEqB8eSwbV1NcOvyJDOjNgUy4uVVmNTko2pqs1cClN8fezzzVfzcA



###
POST http://localhost:8080/users/login
Content-Type: application/json

{
  "username": "test0001",
  "password": "test1234"
}


